node1:
  container_name: node1
  image: centos-marklogic8.0-3
  ports:
   - "10000:8000"
   - "10001:8001"
   - "10002:8002"
   - "9070:9040"
   - "9071:9041"
   - "9072:9042"
   - "9073:9043"
   - "9074:9044"
   - "9075:9045"

  # expose ports for other container
  expose:
   - "13000"
  volumes:
   - /Users/jjoerg/MarkLogic/development/mldemos/mlDocker/shared:/shared

node2:
  container_name: node2
  image: centos-marklogic8.0-3
  ports:
   - "11000:8000"
   - "11001:8001"
  expose:
   - "13000"


 # links:
 #  - node1
  volumes:
   - /Users/jjoerg/MarkLogic/development/mldemos/mlDocker/shared:/shared

node3:
  container_name: node3
  image: centos-marklogic8.0-3
  ports:
   - "12000:8000"
   - "12001:8001"
  expose:
   - "13000"

#  links:
#   - node1
#   - node2
  volumes:
   - /Users/jjoerg/MarkLogic/development/mldemos/mlDocker/shared:/shared
